---
- hosts: win 
  tasks:
    - name: High cpu usage
      win_shell: |
        Get-Counter '\Processor(*)\% Processor Time'|
        select -expand CounterSamples | 
        where{$_.InstanceName -eq '_total' -and $_.CookedValue -gt 70} |
        ForEach{Write-Host $_.CookedValue  -fore Red '%' }
        
      register: result
    - debug: var=result

      #- hosts: localhost
      # tasks:
    - name: mail sending using mail module
      mail:
        host: "cmsitmail.cmsitservices.com"
        port: 587
        username: "madasu.n@cmsitservices.com"
        password: "Naresh&573"
        to:
        - Naresh <madasu.n@cmsitservices.com>
        #        - Sushil Kumar <sushil.kumar@cmsitservices.com>
        # - Kunal Bhatt <kunal.bhatt@cmsitservices.com>
        subject: "ansible-Windows-Clientserver High CPU Utilization Critical Reports"
        #body: "{{ lookup('template','mail_body.j2') }}"
        body: "{% for host in play_hosts %}
        The windows {{ host }}
        High CPU Utilization INFO 
       
        {{ hostvars[host]['result']['stdout'] }}
        {% endfor %}
        
       
        Regards,

        Unix Admins via Ansible" 
      delegate_to: localhost
      # run_once: True
      when: result.stdout
