---
- hosts: win 
  tasks:
    - name: windows open ports
      win_shell: |
        netstat -a
      register: result
    - debug: var=result

      #- hosts: localhost
      # tasks:
    - name: mail sending using mail module
      mail:
        host: "cmsitmail.cmsitservices.com"
        port: 587
        username: "madasu.n@cmsitservices.com"
        password: "Naresh*573"
        to:
        - Naresh <madasu.n@cmsitservices.com>
        #        - Sushil Kumar <sushil.kumar@cmsitservices.com>
        # - Kunal Bhatt <kunal.bhatt@cmsitservices.com>
        subject: "ansible-Windows-Clientserver Open ports"
        #body: "{{ lookup('template','mail_body.j2') }}"
        body: "{% for host in play_hosts %}
        The windows {{ host }}
        Server open ports
       
        {{ hostvars[host]['result']['stdout'] }}
        {% endfor %}
        
       
        Regards,

        Unix Admins via Ansible" 
      delegate_to: localhost
      # run_once: True
