---
- hosts: win 
  tasks:
    - name: windows Disk  information
      win_shell: |
        date
        #get-volume
        gwmi win32_logicaldisk | Format-Table DeviceId, MediaType, @{n="Size";e={[math]::Round($_.Size/1GB,2)}},@{n="FreeSpace";e={[math]::Round($_.FreeSpace/1GB,2)}}
      register: result
#    - debug: var=result

      #- hosts: localhost
      # tasks:
    - name: mail sending using mail module
      mail:
        host: "cmsitmail.cmsitservices.com"
        port: 587
        username: "madasu.n@cmsitservices.com"
        password: "Naresh*573"
        to:
        - Naresh <madasu.n@cmsitservices.com>
        #        - Sushil Kumar <sushil.kumar@cmsitservices.com>
        # - Kunal Bhatt <kunal.bhatt@cmsitservices.com>
        subject: "ansible-Windows-Clientserver Windows Disk Information"
        #body: "{{ lookup('template','mail_body.j2') }}"
        body: "{% for host in play_hosts %}
        The windows {{ host }}
        Disk INFO on {{ hostvars[host]['result']['stdout'] }}
        {% endfor %}
        
       
        Regards,

        Unix Admins via Ansible" 
      delegate_to: localhost
      # run_once: True
