---
- hosts: win 
  tasks:
    - name: Install all critical and security updates
      win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        state: installed
        log_path: c:\ansible_upadte30.txt
      register: update_result

    - name: Fetch a info file
      fetch: 
        src: C:\ansible_upadte30.txt 
        dest: /root/windows/success/ansible_upadte30.txt 
        flat: yes

    - name: mail sending using mail module
      mail:
        host: "cmsitmail.cmsitservices.com"
        port: 587
        username: "madasu.n@cmsitservices.com"
        password: "Naresh*573"
        to:
        - Kunal Bhatt <kunal.bhatt@cmsitservices.com>
        cc:
        - Naresh <madasu.n@cmsitservices.com>
        - Sushil Kumar <sushil.kumar@cmsitservices.com>
        # - Kunal Bhatt <kunal.bhatt@cmsitservices.com>
        subject: "ansible-Windows-Clientserver Update Reports"
        body: "Windows {{ ansible_hostname }} has been updated successfully."
        attach:
        - /root/windows/success/ansible_upadte30.txt
      delegate_to: localhost
      # run_once: True
     
    - name: Reboot host if required
      win_reboot:
      when: update_result.reboot_required
