---
- hosts: nxengine 
  tasks:
    - shell: |
        #!/bin/bash
        #date -d "today + 7 days" +"%d %b %Y"
        /usr/bin/free | awk '/Mem/{printf("RAM Usage: %.2f%\n"), $3/$2*100}' |  awk '{print $3}' | awk '{ if($1 > 75) print $0;}'
        #/usr/bin/cat /proc/loadavg | awk '{print $1}' | awk '{ if($1 > 0) printf("Current CPU Utilization is: %.2f%\n"), $0;}'
      register: result
   # - debug: var=result

    - name: send mail
      mail:
        host: "cmsitmail.cmsitservices.com"
        port: 587
        username: "madasu.n@cmsitservices.com"
        password: "Naresh*573"
        to:
        - Sushil Kumar <sushil.kumar@cmsitservices.com>
        - Kunal Bhatt <kunal.bhatt@cmsitservices.com>
          #- Naresh <madasu.n@cmsitservices.com>
        cc:
        - Naresh <madasu.n@cmsitservices.com>
          #- Sushil Kumar <sushil.kumar@cmsitservices.com>
          #- Kunal Bhatt <kunal.bhatt@cmsitservices.com>
          #subject: "ansible-Clientserver Disk-Usage-Reports"
        subject: "Ansible High-Memory-Usage-Alert"
        #body: "{{ lookup('template','mail_body.j2') }}"
        body: "{% for host in play_hosts %}
        The {{ host }}
      
        High Memory Usage on {{ hostvars[host]['result']['stdout'] }}

        {% endfor %}



        Regards,

        Unix Admins via Ansible "
      delegate_to: localhost
      run_once: True
      when: result.stdout 
