---
- hosts: localhost
  tasks:
    - name: shedule tasks
      cron:
        hour: "*"
        minute: "*/5"
        month: "*"
        job: "/usr/bin/ansible-playbook /root/Linux/Nexthink-Project/NX-High-Memory-usage.yml"
        state: present 

        #  - name: shedule tasks
        #cron:
        #hour: "*"
        #minute: "*/5"
        #month: "*"
        #job: "/usr/bin/ansible-playbook /var/lib/awx/projects/Linux/cpu-reports.yml"
        #state: present      
