---
- hosts: nexthink
  tasks:
  - name: check url status
    uri:
      url: http://10.197.9.183
      validate_certs: False
      #    ignore_errors: yes
    register: result
  - debug: var=result

