---
- hosts: ansibleclient
  tasks:
    - name: display the server network details
      shell: nmcli
      register: result
    - debug: var=result

    - name: mail sending using mail module
      mail:
        host: "cmsitmail.cmsitservices.com"
        port: 587
        username: "madasu.n@cmsitservices.com"
        password: "Naresh*573"
        to:
        - Naresh <madasu.n@cmsitservices.com>
          #cc:
          #- Sushil Kumar <sushil.kumar@cmsitservices.com>
          #- Kunal Bhatt <kunal.bhatt@cmsitservices.com>
        subject: "ansible-Clientserver Network-Ethernet-Reports"
        #body: "{{ lookup('template','mail_body.j2') }}"
        body: "{% for host in play_hosts %}
        The {{ host }}
        Network Information {{ hostvars[host]['result']['stdout'] }}
        
       
        {% endfor %}



        Regards,

        Unix Admins via Ansible "
      delegate_to: localhost
      run_once: True
      # when: not result.stdout
