---
- hosts: nagiossrv.com
  tasks:
    - name: check url status
      uri:
        url: http://10.197.9.203
      ignore_errors: yes
      register: result

    - name: send mail
      mail:
        host: "cmsitmail.cmsitservices.com"
        port: 587
        username: "madasu.n@cmsitservices.com"
        password: "Naresh*573"
        to:
        - Naresh <madasu.n@cmsitservices.com>
          #cc:
          #- Sushil Kumar <sushil.kumar@cmsitservices.com>
          #- Kunal Bhatt <kunal.bhatt@cmsitservices.com>
          #subject: "ansible-Clientserver Disk-Usage-Reports"
        subject: "Apache Webserver URL-Status Critical Alert"
        #body: "{{ lookup('template','mail_body.j2') }}"
        body: "{% for host in play_hosts %}
        The {{ host }}
      
        Apache webserver is not working  
        
        Error code is:
        
                {{ result | to_nice_json }}

        {% endfor %}



        Regards,

        Unix Admins via Ansible "
      delegate_to: localhost
      run_once: True
      #when: result.stdout
      #when: result|failed 
      when: result is failed
